### ISSUE TITLE
Bug kill jetster traitor

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#11]
If a jester is killed by a traitor, nothing happens.

**Comment by dok441** [comment]
If the jester is killed by a serial killer, nothing happens.

**Comment by dok441** [comment]
Why do you think it is not so?! Did you check?!

**Comment by TimGoll** [comment]
It seems to happen only for you

**Comment by Alf21** [comment]
This is reasoned by another enabled winstate
