### ISSUE TITLE
bug infected and jackal

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#13]
Я обнаружил проблему, если ты был шакалом, ты обратил человека в сообщника, тебя убивает зараженный, твой напарник живой и ты его пытаешься убить, твой урон по нему не проходит, то есть, ты его не можешь убить, а хост зараженных его убил, когда я его попросил.

**Comment by Histalek** [comment]
As this issue is a year old and many things have changed i will close it.

Feel free to reopen if you encounter the problem again :)
