### ISSUE TITLE
Do not revive when infected by the jester.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#14]
Если шут станет зараженным и он попытается кого-то убить, то убитый человек не станет зараженным.

**Comment by Alf21** [comment]
"Wenn der Narr infiziert wird und versucht, jemanden zu töten, wird die getötete Person nicht infiziert."

**Comment by Histalek** [comment]
I can't reproduce this problem so it might already be fixed.

Feel free to reopen if this problem happens again :)
