### ISSUE TITLE
Error of revival

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#24]
Again the mistake of reviving the left man, not the jester, after the death of the murderer. I have been writing about this for a long time, but still how much time has not passed, it is relevant.

RU:
Опять ошибка с возрождением левого человека, а не шута после смерти убийцы. Я уже давно об этом писал, но все еще это актуально.

**Comment by TimGoll** [comment]
Actually I have no idea what you're talking about. Maybe you can explain it better?

**Comment by Histalek** [comment]
Also please let us know what your ConVar settings for the Jester are. A screenshot of the ULX window with the jester winstates visible for example :)
