### ISSUE TITLE
Transfer the translation.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#26]
You can make the entire translation into 1 file. So-how to run from file to file every time changing lines like " killer: ChatPrint("You were killed, because you killed the Jester!")" Is a bit annoying and will be more convenient if everything is in the shared file where the main translation of the role is located.

**Comment by Histalek** [comment]
This was fixed by c7e8ab7d1d0b33a86961598e27413273d1b5d59d .
The mentioned ChatPrint now also exists as a language string.
