### ISSUE TITLE
Jester is able to damage other players

### ISSUE THREAD

**Issue by Vextrom** [TTT-2/ttt2-role_jes#27]
I'm running TTT2 commit 24521f128f13ce206e2fadd090e0ce4698745d2f (2-11-2020)
and jester commit b1866c608d39a040f176b64857bcdeb2d8e30039 (2-11-2020)

Anyone who holds the jester role is able to damage other players. This should not be happening. It happens regardless of the role being selected naturally by the server or if the role is forced by an admin.

**Comment by TimGoll** [comment]
Thanks! I rewrote the jester role since it had too many problems. I will take care of it

**Comment by Vextrom** [comment]
Completely understandable. I'm happy to hear that.

Thanks for the good work you've done. 👍

**Comment by TimGoll** [comment]
Ah, btw, I fixed it in the last commit. Please update the jester and TTT2 as well.

**Comment by TimGoll** [comment]
Since this is fixed, I'll close this. Please reopen if you encounter the problem again
