### ISSUE TITLE
added IsPlayer check ERROR

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#29]
When a person dies, it writes an error to the console
[ERROR] addons/ttt2-role_jes-master/lua/autorun/server/sv_jester_winstates.lua:225: attempt to call a nil value
  1. unknown - addons/ttt2-role_jes-master/lua/autorun/server/sv_jester_winstates.lua:225
   2. fn - addons/ttt2-role_jes-master/lua/autorun/server/sv_jester_winstates.lua:274
    3. Run - addons/ulib/lua/ulib/shared/hook.lua:109
     4. unknown - gamemodes/terrortown/gamemode/server/sv_player.lua:1317
      5. TakeDamageInfo - [C]:-1
       6. unknown - gamemodes/terrortown/gamemode/shared/sh_main.lua:184

**Comment by Histalek** [comment]
i have possibly fixed the error with dcc088211887f7d85982dd6090c2add5525fea57.

Please reopen if the error happens again.
