### ISSUE TITLE
Jester alert errors

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#30]
As we can see in the screenshot, I became a jester, but it is written on top, there are no jesters in the round. Also often says, the fool has, but it is in fact present. Also, there is still no fixed duplicate notification depending on the number of players, if there are 100 people on the server, let's say there will be 20 units of militia...
![Безымянный](https://user-images.githubusercontent.com/7480655/74612717-14031500-5119-11ea-94a5-9459db546285.png)

**Comment by Histalek** [comment]
This is now fixed :)
