### ISSUE TITLE
Jester announcement placeholder bug

### ISSUE THREAD

**Issue by tobi-nb** [TTT-2/ttt2-role_jes#31]
Hi,

ich wollte kurz melden, dass es aktuell (Version 0.6b) 2 Bugs mit des Jester existieren:

**Bugs:
1.**
Der Jester wird immer zwei Mal angekündigt.
![ttt_waterworld_remastered0008](https://user-images.githubusercontent.com/54220297/74718237-15743080-5232-11ea-844a-61b6bf9f55f6.jpg)

**2.** (Leider kein Screenshot)
Wenn man Traitor ist, wird einem ja oben rechts angkeündigt, welcher Spieler Jester ist. Dort wird aber nur der Placeholder 

> '{player_name}' is Jester'

angezeigt.

Version: 0.6b (steht so in der Log, das Workshop Addon ist ja eigentlich schon auf 0.6.1b..?)
Steam-Collection: https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

**Comment by Histalek** [comment]
Beide Probleme sollten jetzt behoben sein :)
