### ISSUE TITLE
Jester wins when killed after roundending

### ISSUE THREAD

**Issue by tobi-nb** [TTT-2/ttt2-role_jes#32]
In der Version 0.6b tritt ein interessanter Bug des Jesters auf:
Wenn er in einer Runde spawnt, NICHT gewinnt, dann aber nach dem RundenENDE getötet wird, gewinnt er in der nächsten Runde, selbst wenn es dort keinen Jester gibt.

Der entsprechende Auszug aus der Log:

> L 02/21/2020 - 20:46:48: 00:34.97 - DMG: 	 ScrubHard [innocent] damaged JMinator [traitor] for 45 dmg
> L 02/21/2020 - 20:46:48: 00:35.09 - DMG: 	 JMinator [traitor] damaged ScrubHard [innocent] for 72 dmg
> L 02/21/2020 - 20:46:48: 00:35.30 - DMG: 	 JMinator [traitor] damaged Crysis [detective] for 116 dmg
> L 02/21/2020 - 20:46:48: 00:35.30 - KILL:	 JMinator [traitor] killed Crysis [detective]
> L 02/21/2020 - 20:46:49: 00:36.32 - DMG: 	 ScrubHard [innocent] damaged JMinator [traitor] for 78 dmg
> L 02/21/2020 - 20:46:49: 00:36.32 - KILL:	 ScrubHard [innocent] killed JMinator [traitor]
> L 02/21/2020 - 20:46:50: 00:36.77 - DMG: 	 Drizzel [traitor] damaged Schmanuel [survivalist] for 39 dmg
> L 02/21/2020 - 20:46:51: 00:37.58 - DMG: 	 Drizzel [traitor] damaged Schmanuel [survivalist] for 77 dmg
> L 02/21/2020 - 20:46:51: 00:37.58 - KILL:	 Drizzel [traitor] killed Schmanuel [survivalist]
> L 02/21/2020 - 20:47:12: 00:59.14 - DMG: 	 ScrubHard [innocent] damaged CURRY-Wandton [jester] for 45 dmg
> L 02/21/2020 - 20:47:23: 01:09.77 - DMG: 	 ScrubHard [innocent] damaged Drizzel [traitor] for 113 dmg
> L 02/21/2020 - 20:47:23: 01:09.77 - KILL:	 ScrubHard [innocent] killed Drizzel [traitor]
> L 02/21/2020 - 20:47:23: Round ended.
> L 02/21/2020 - 20:47:23: Result: innocents win.
> L 02/21/2020 - 20:48:03: Round proper has begun...
> L 02/21/2020 - 20:48:04: Round ended.
> L 02/21/2020 - 20:48:04: Result: jesters win.

Mit folgenden Einstellungen läuft der Jester (logischerweise aktiviert, habe ihn nach diesem Bug aber vorerst deaktiviert):
![ttt_casino_b20000](https://user-images.githubusercontent.com/54220297/75068456-8005c480-54ef-11ea-9a00-a204bb7117b2.jpg)

Servercollection: 
https://steamcommunity.com/sharedfiles/filedetails/?id=849222406

**Comment by TimGoll** [comment]
Also ich konnte es alleine nicht testen, aber ich bin mir sehr sicher es gefixt zu haben.

Abgesehen davon, danke für den guten Bugreport. Damit konnte ich direkt was anfangen und habe den Fehler sofort gefunden.
