### ISSUE TITLE
Jester Respawn Time in ConVar related to winstate & toggle Jester Icon for traitors

### ISSUE THREAD

**Issue by ToFurkie** [TTT-2/ttt2-role_jes#34]
Two requests for the Jester role, not really issues

1. Make a setting for winstates that respawn Jester in a set time from instant (zero) to 10 seconds. If set to 0, Jesters can spawn instantly and a round will continue even if the killer is the last of an opposing role (last innocent alive kills a Jester, the Jester will respawn as an innocent and the round will continue until innocent Jester or all opposing roles die). Maybe add another toggle setting for Jesters to spawn either on own dead body, killers body, or at map spawn, but this isn't necessary

2. Enable/Disable Jester icons for traitors to see when playing

**Comment by cuteexe** [comment]
ohh and how about respawning the jester at a spawnpoint since usually the jester just gets killed twice.

**Comment by TimGoll** [comment]
since the jester is completely reworked, this is no longer valid
