### ISSUE TITLE
Server freezes if killed by Fart Rocket

### ISSUE THREAD

**Issue by cuteexe** [TTT-2/ttt2-role_jes#35]
the server freezes if killed by fart rocket using winstate 5. just noticed the fart rocket is not on the workshop anymore it used to be a traitor weapon which is a sniper rifle. if you hit someone they will get 1 damage the screen starts to shake the fly up and die. (i think by world?) a traitor hit a jester by accident sicne he moved infront of someone and well the server freezed.

**Comment by Histalek** [comment]
Sadly i can't reproduce this issue. For testing i used [this fart rocket](https://steamcommunity.com/sharedfiles/filedetails/?id=1375209708) from the Workshop.
Please try using that version and report back if it works for you or not. Thank you!

**Comment by cuteexe** [comment]
alright replaced the original version we had with this updated one. will try again once i got time for it. sidenote: i am using the jester role from the workshop i hope its as up to date as this one

**Comment by Histalek** [comment]
Thank you :) and using the workshop jester is completely fine as it is completely up to date right now

**Comment by cuteexe** [comment]
well i did report earlier on the workshop comments that we were haveing issues once the jester gets moved to afk which also ended up freezing our server. we reenabled the addon since the last update to the workshop. it sound very similar. so my guess would be that the update wasn't related to our issue. it might be a combination of addons causing this idk. actually will test now using bots. just found out i have time right now.

**Comment by cuteexe** [comment]
well just tried using the fart rocket you linked and it is working fine. this seams to be a fixed version. when the freeze happened the last thing the console said was something like 

ServerLog: 00:42.46 - KILL:      Bot03 [jester] killed Bot03 [jester]

with this fart rocket it says i killed him so i get killed

**Comment by cuteexe** [comment]
alright tried again using the original version and i can reproduce. [here](http://shy.noip.me/i/qa.rar) is a download link to the original version which somehow got deleted from the workshop

**Comment by TimGoll** [comment]
Hmm, it's probably not deleted without a reason

**Comment by cuteexe** [comment]
well still imo this plugin shouldn't freeze the server if the jester somehow gets killed by himself. there might be other weapons which could do the same. not so much fun to find out that whatever weapon crashes the server when you shoot the jester by accident. i mean ofc i update to the other version sicne it sets the damage better, might even fix the fixed version and set the damage type to DMG_BLAST so that some classes would survive it. but still as i said an addon should not in any way be able to crash the server.

**Comment by cuteexe** [comment]
it also happens if i kill the jester using ulx slay command

**Comment by Histalek** [comment]
I agree that server freezes because of addons should never happen. Normally selfkills of the jester should not be a problem, but i may have misplaced the check. also worldkills might be a problem, i will add another check

**Comment by cuteexe** [comment]
to reproduce easily just spawn a bunch of bots make one jester kill jester using ulx slay from server console. and ofc set killstate to 5.

actually it might even work if you set yourself jester and use kill in console? i will try that

**Comment by Histalek** [comment]
The Github Version should now be fixed :) 
Though i can't give an ETA on when the Workshop Version will be updated as I can't do it.

Thank you for reporting and testing this!
