### ISSUE TITLE
Prevent non-direct player damage

### ISSUE THREAD

**Issue by Alf21** [TTT-2/ttt2-role_jes#41]
Please add a Jester ConVar to disable no direct player damage (default: false), e.g. for explosion damage etc (C4, frags, ...). esp. explosion and fire damage. Ref. from WS:

> Tons of jester mods (every single version leading up to this point, really) have it disabled, and it almost never gives them away. In the scheme of things, the Jester having a small chance of getting revealed is relatively minor compared to the fact that...

> ...the jester can currently die to traitor items. Like SLAMs and Barnacles and C4 and Jihads and Frags and every god dang other T weapon. That's not RDMing. That's playing a T. Those should not be completely unusable simply because a Jester is somewhere on the entire map.

> Not to mention a Jester can grab and explosive barrel and just run with it, and anyone who shoots it wins them the game, and they only need to get it into any firefight anywhere to win.

> This current version is nearly unusable, sadly. We removed it from the game. I do hope you eventually make a version with at least the option of turning off fire/explosion/drowning/etc damage.

Link to discussion: https://steamcommunity.com/sharedfiles/filedetails/?id=1363049665

**Comment by Alf21** [comment]
Includes #38

**Comment by Histalek** [comment]
implemented by #43
