### ISSUE TITLE
jester crashing server

### ISSUE THREAD

**Issue by deathy108** [TTT-2/ttt2-role_jes#44]
if a jester shoots himself with the russian roulette pistol it crashes the full server

not sure if it works with killbind or goldun deagle. it might.

jester was using winstate 5
![image](https://user-images.githubusercontent.com/64363173/80309093-915a9e00-87ca-11ea-8a89-0c8eb74ffff1.png)

**Comment by Histalek** [comment]
I suspect you are using the workshop version, correct? if so that bug is known and already fixed. I can't give you an ETA on when the Workshop addon will be updated, we will do it as soon as possible.

Nonetheless thank you for reporting!

**Comment by Histalek** [comment]
as this is already fixed in the masterbranch i'll close this.
