### ISSUE TITLE
jester broken after role selection rework

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_jes#45]
![image](https://user-images.githubusercontent.com/36534723/82119496-62a76600-977f-11ea-99c6-417166897b5c.png)

[ERROR] addons/ttt2-role_jes-master/lua/autorun/server/sv_jester_winstates.lua:152: attempt to call global 'GetSelectableRoles' (a nil value)
  1. unknown - addons/ttt2-role_jes-master/lua/autorun/server/sv_jester_winstates.lua:152
   2. fn - addons/ttt2-role_jes-master/lua/autorun/server/sv_jester_winstates.lua:226
    3. Run - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109
     4. unknown - addons/ttt2-master/gamemodes/terrortown/gamemode/server/sv_player.lua:975

I think the jester need an update because after the role selection rework he stops working.
[i have winstate 6]

**Comment by TimGoll** [comment]
@saibotk Maybe you could replace this with the new function name
