### ISSUE TITLE
The translation doesn't work.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#46]
The translation of the working condition definition does not work, the translation is taken from the original.
![Безымянный](https://user-images.githubusercontent.com/7480655/83048600-82c60780-a052-11ea-87b6-ba2d5642c201.png)

**Comment by TimGoll** [comment]
have you added all those translations: https://github.com/TTT-2/ttt2-role_jes/blob/master/lua/lang/english/jester.lua

**Comment by dok441** [comment]
Maybe my mistake.
