### ISSUE TITLE
Jester public role bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_jes#47]
## DISCLAIMER
**All the tests I've done have been done with winstate 6, I don't know with the others but I think all the winstates in which those who kill the Jester die are subject to this problem**

## Your version of TTT2/Jester (mandatory)

Leave one of the following:
- Latest GitHub version

## Describe the bug (mandatory)
If the person who killed him is identified, the death of the jester will be confirmed (although obviously he is reborn) 
![image](https://user-images.githubusercontent.com/36534723/83349890-5eab4480-a338-11ea-9040-69fe6531a458.png)
confirmation of the death of the jester will make public his role
after that you only need a quick fully resfresh of the scoreboard to activate the bug 
and the other player should see the jester new role
![image](https://user-images.githubusercontent.com/36534723/83350173-92876980-a33a-11ea-87e5-21e63b0648ba.png)
In this case is marker

## Expected behaviour

The new jester role should not visible publicly

## To reproduce

Steps to reproduce the behaviour:

Player1=Jester;
Player2=Random Role[except of course clairvoyant and infected (they have special behaviur with him)]
Player3=Random Role (not as the same team as the respawned Jester)

1. Player2 kills Player1 (So Player2 will die because he kill the jester)
2. Player2 body must be identify, no matter from whom (thus the death of the jester is confirmed but obviously he is respawned) 
3. Refresh the scoreboard, you can use ulx respawn "Player2" in order to do that (the command will full refresh the scoreboard instantly)
4. Player3 press tab and he can see the Player1 new role

Of course there are other ways to do it even without using commands but this is faster to show the bug, for example, an identified role that respawn or for other reasons
It happened to us many times in the game normally

**PS:** there is the video with the same procedure described

## Video
https://youtu.be/CVAFwp2oH5E

## Error or something  ?

No error in serverside and client side console

**Comment by saibotk** [comment]
Side note: A huge thank you for your excellent bug reports, there is always a video and anything we could ask for. This in general makes fixing those bugs way easier in most of the cases!
So keep up the good work! :heart:

**Comment by ThePlatinumGhost** [comment]
I find today that this can also happened with Unknown
keep in mind when this will be fixed!

**Comment by ThePlatinumGhost** [comment]
i think is fixed with commit 91af1467ab277e4598f9fcf31058a6a68fd01634 so i will close the issue, i'm not able to replicate this bug after the commits
if the bug reoccur i will reopen the issue

**Comment by ThePlatinumGhost** [comment]
I reopened this since the bug's still happening but now it can't be replicated with the procedure written on **TO REPRODUCE**. After I'll find a new way to replicate it, I will write it here

**Comment by ThePlatinumGhost** [comment]
**NEW WAYS TO REPRODUCE**
ignore the legend from top
Player1 e Player2: Normal role that can deals damage (and not infected)

with JESTER or UNKNOWN
1. Player1 kill Jester/Unknown
2. Player2 identify and confirm Jester/Unknown before he respawn
3. Now Jester/Unknown new role is public
