### ISSUE TITLE
Absence of victory conditions.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#48]
As you can see in the screenshot, the round began, but the jester did not write what version of victory he had. Also at this point, slay was issued to the traitor and his body was identified.
![Без названия (1)](https://user-images.githubusercontent.com/7480655/83964608-dcca9680-a8b6-11ea-9d51-8b4b2b380eb3.jpg)

**Comment by TimGoll** [comment]
I really don't see how this could happen, because it is executed in `TTTBeginRound`. The only idea I have is that some other addon has a `return true/false` in this hook and therefore cancels the hook.

**Comment by TimGoll** [comment]
Since the jester gor completely reworked, I guess this is probably fixed as well. Please reopen, if it still exists.
