### ISSUE TITLE
One role, different teams

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_jes#49]
The shute had the goal of dying and getting the role of its enemy. He dies of an accomplice, gets an accomplice, but the bottom line is there 's no team, he kind of becomes for an innocent accomplice, but is that right?! After all, he should get a jackal team by idea, because if he killed a traitor, he became a traitor. How do you consider?!
![123](https://user-images.githubusercontent.com/7480655/84121009-41b0f880-aa3f-11ea-88e4-4dc822b54c88.png)

**Comment by TimGoll** [comment]
Who's the shute? The unknown?

**Comment by dok441** [comment]
jester

**Comment by TimGoll** [comment]
So the jester is killed by a sidekick? And then he becomes a sidekick without a team?

**Comment by dok441** [comment]
yes

**Comment by TimGoll** [comment]
This is probably no longer a valid issue, because the jester changed completely. Please reopen if this issue still exists
