### ISSUE TITLE
QOL Issue - Give an option to let Jester respawn at a random worldspawn instead of on the body

### ISSUE THREAD

**Issue by CptHaxray** [TTT-2/ttt2-role_jes#57]
Description:
This isn't a bug in the normal sense, but rather a major gameplay issue that became apparent while running Jester on a public server. Since by Default, jester only respawns at their body, Jesters would always end up spawn camped whenever they managed to be successfully killed. While this issue does not apply if the Jester has the autowin condition enabled, it is a major issue in regards to every other winstate.

Notes:
- Adding an option to let Jester respawn at a world spawn instead of at their body would solve  the spawn camp issues, and it was a fix i've seen implemented on servers several times in the past. The Restless role has a convar option that allows it to choose between respawning at the body and respawning at a world spawn, so that could be useful as a reference if needed.
-  
- Im aware this isn't a bug in the normal sense, but as it is a major gameplay issue I felt it was worth writing up as an issue.

**Comment by saibotk** [comment]
Thank you for your feedback.
Issues do not necessarily mean it is a bug. And we are always happy about ideas and general feedback in issues 😉

And yes that would be a good thing to have. As soon as one of us has the spare time and interest this might be implemented.

Thank you

**Comment by TimGoll** [comment]
This is no longer relevant to the current jester. I think this might also be already be a feature of the swapper
